<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="图书.aspx.cs" Inherits="模拟网上图书馆.读者.图书" %>
<%@ Register TagName="foot" TagPrefix="myctl" Src="~/简单的自定义控件/footer.ascx"%>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="../样式表/管理.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
         <myctl:foot ID="myfoot" runat="server" />
    <div class="header">
        <asp:Label ID="Label1" runat="server" Text="欢迎管理员：" CssClass="a1"></asp:Label>
        <asp:Button ID="Button1" class="a2" runat="server" Text="退出登录" OnClick="Button1_Click" />
        </div>
        <div class="main">
            <div class="left">
                <asp:Calendar ID="Calendar1" runat="server" CssClass="c1"></asp:Calendar>
                <a class="a1" href="读者.aspx">已注册读者</a>
                <a class="a2" href="图书.aspx">已上架图书</a>
                <a class="a3" href="上架新书.aspx" target="_blank">上架新书</a>
                <a class="a4" href="借阅信息.aspx" target="_blank">管理借阅</a>
            </div>
            <div class="chart">
                <h2>已上架图书</h2>
                <asp:DropDownList ID="DropDownList1" runat="server" CssClass="d1" AutoPostBack="True" DataSourceID="SqlDataSource2" DataTextField="类型名称" DataValueField="类型编号">
                    
                </asp:DropDownList>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=F:\终极闪光版\模拟网上图书馆\模拟网上图书馆\数据\模拟图书馆.mdf;Integrated Security=True;Connect Timeout=30" ProviderName="System.Data.SqlClient" SelectCommand="SELECT * FROM [图书类型表]"></asp:SqlDataSource>
                <asp:GridView ID="gv" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" CssClass="g1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="图书编号">
                    <Columns>
                        <asp:BoundField DataField="图书编号" HeaderText="图书编号" SortExpression="图书编号" ReadOnly="True" />
                        <asp:BoundField DataField="书名" HeaderText="书名" SortExpression="书名" />
                        <asp:BoundField DataField="作者" HeaderText="作者" SortExpression="作者" />
                        <asp:BoundField DataField="出版社" HeaderText="出版社" SortExpression="出版社" />
                        <asp:BoundField DataField="出版日期" HeaderText="出版日期" SortExpression="出版日期" />
                        <asp:BoundField DataField="上架日期" HeaderText="上架日期" SortExpression="上架日期" />
                        <asp:BoundField DataField="图书简介" HeaderText="图书简介" SortExpression="图书简介" />
                        <asp:BoundField DataField="图书类_类型编号" HeaderText="图书类_类型编号" SortExpression="图书类_类型编号" />
                        <asp:BoundField DataField="图书单价" HeaderText="图书单价" SortExpression="图书单价" />
                        <asp:BoundField DataField="上架数量" HeaderText="上架数量" SortExpression="上架数量" />
                        <asp:BoundField DataField="剩余数量" HeaderText="剩余数量" SortExpression="剩余数量" />
                        <asp:BoundField DataField="文本路径" HeaderText="文本路径" SortExpression="文本路径" />
                    </Columns>
                </asp:GridView>
                <br />
                <br />
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=F:\终极闪光版\模拟网上图书馆\模拟网上图书馆\数据\模拟图书馆.mdf;Integrated Security=True;Connect Timeout=30" ProviderName="System.Data.SqlClient" SelectCommand="SELECT * FROM [图书信息表] WHERE ([图书类_类型编号] = @图书类_类型编号)" DeleteCommand="DELETE FROM [图书信息表] WHERE [图书编号] = @original_图书编号" InsertCommand="INSERT INTO [图书信息表] ([图书编号], [书名], [作者], [出版社], [出版日期], [上架日期], [图书简介], [图书类_类型编号], [图书单价], [上架数量], [剩余数量], [文本路径]) VALUES (@图书编号, @书名, @作者, @出版社, @出版日期, @上架日期, @图书简介, @图书类_类型编号, @图书单价, @上架数量, @剩余数量, @文本路径)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [图书信息表] SET [书名] = @书名, [作者] = @作者, [出版社] = @出版社, [出版日期] = @出版日期, [上架日期] = @上架日期, [图书简介] = @图书简介, [图书类_类型编号] = @图书类_类型编号, [图书单价] = @图书单价, [上架数量] = @上架数量, [剩余数量] = @剩余数量, [文本路径] = @文本路径 WHERE [图书编号] = @original_图书编号">
                    <DeleteParameters>
                        <asp:Parameter Name="original_图书编号" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="图书编号" Type="Int32" />
                        <asp:Parameter Name="书名" Type="String" />
                        <asp:Parameter Name="作者" Type="String" />
                        <asp:Parameter Name="出版社" Type="String" />
                        <asp:Parameter Name="出版日期" Type="DateTime" />
                        <asp:Parameter Name="上架日期" Type="DateTime" />
                        <asp:Parameter Name="图书简介" Type="String" />
                        <asp:Parameter Name="图书类_类型编号" Type="Int32" />
                        <asp:Parameter Name="图书单价" Type="Decimal" />
                        <asp:Parameter Name="上架数量" Type="Int32" />
                        <asp:Parameter Name="剩余数量" Type="Int32" />
                        <asp:Parameter Name="文本路径" Type="String" />
                    </InsertParameters>
                    <SelectParameters>
                        <asp:ControlParameter ControlID="DropDownList1" DefaultValue="1" Name="图书类_类型编号" PropertyName="SelectedValue" Type="Int32" />
                    </SelectParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="书名" Type="String" />
                        <asp:Parameter Name="作者" Type="String" />
                        <asp:Parameter Name="出版社" Type="String" />
                        <asp:Parameter Name="出版日期" Type="DateTime" />
                        <asp:Parameter Name="上架日期" Type="DateTime" />
                        <asp:Parameter Name="图书简介" Type="String" />
                        <asp:Parameter Name="图书类_类型编号" Type="Int32" />
                        <asp:Parameter Name="图书单价" Type="Decimal" />
                        <asp:Parameter Name="上架数量" Type="Int32" />
                        <asp:Parameter Name="剩余数量" Type="Int32" />
                        <asp:Parameter Name="文本路径" Type="String" />
                        <asp:Parameter Name="original_图书编号" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div>
        </div>

    </form>
</body>
</html>
